apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kubectl-apply-file
  namespace: tekton-pipelines
spec:
  workspaces:
  - name: ws
  params:
  - name: filePath
    default: /workspace/ws/vnf-frr.yaml
  steps:
  - name: apply
    image: registry.k8s.io/kubectl:v1.30.0
    command: ["kubectl"]
    args: ["apply","-f","$(params.filePath)"]
