apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kubectl-apply-file
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: ws
      description: The workspace containing the manifest file
  params:
  - name: filePath
    description: Path to the manifest file to apply
  # [MỚI] Thêm tham số namespace
  - name: namespace 
    description: Namespace to deploy resource into
    default: "default"
  steps:
  - name: apply
    image: bitnami/kubectl:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo ">>> Checking file: $(params.filePath)"
        if [ ! -f $(params.filePath) ]; then
            echo "ERROR: File $(params.filePath) does not exist!"
            exit 1
        fi
        
        echo ">>> Deploying to Namespace: $(params.namespace)"
        # Thêm cờ -n để chỉ định namespace đích
        kubectl apply -f $(params.filePath) -n $(params.namespace)