apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kubectl-wait
  namespace: core-router
spec:
  params:
  - name: namespace
  - name: labelSelector
  steps:
  - name: wait
    image: localhost:32000/kubectl:1.30  # local registry — no internet dependency
    command: ["kubectl"]
    args: ["-n","$(params.namespace)","rollout","status","deploy","-l","$(params.labelSelector)","--timeout=180s"]
