apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kubectl-scale
  namespace: core-router
spec:
  params:
  - name: namespace
  - name: deployName
  - name: replicas
  steps:
  - name: scale
    image: registry.k8s.io/kubectl:v1.30.0
    command: ["kubectl"]
    args: ["-n","$(params.namespace)","scale","deploy","$(params.deployName)","--replicas=$(params.replicas)"]
