apiVersion: v1
kind: ConfigMap
metadata:
  name: frr-cfg
  namespace: core-router
data:
  frr.conf: |
    frr defaults traditional
    hostname frr
    service integrated-vtysh-config
    line vty
  vtysh.conf: |
    service integrated-vtysh-config
