apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tasks/task-kubectl-apply-file.yaml
  - tasks/task-kubectl-get.yaml
  - tasks/task-kubectl-scale.yaml
  - tasks/task-kubectl-wait.yaml
  - tasks/task-kubectl-run.yaml
  - tasks/task-bb-sh.yaml
  - tasks/task-kubectl-get-all.yaml
  - pipeline-vnf-wide.yaml
  - vnf-inputs.yaml
  - tekton-admin.yaml
  - ns-vnf.yaml
  - config-frr.yaml
  - vnf-frr.yaml