apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: vnf-lcm-wide-run-
  namespace: tekton-pipelines
spec:
  taskRunTemplate:
    serviceAccountName: tekton-admin
  pipelineRef:
    name: vnf-lcm-wide
  workspaces:
  - name: ws
    configMap:
      name: vnf-inputs
  params:
  - name: ns
    value: vnf
  - name: deployName
    value: vnf-frr
  - name: labelSelector
    value: app=vnf-frr
